### ISSUE TITLE
What about database migrations?

### ISSUE THREAD

**Issue by wederer** [jawj/mostly-ormless#1]
I found your comment on hackernews and thus this document.
What are you doing with your database migrations? Do you use your own solution or a package?

**Comment by jawj** [comment]
Right now I'm just doing manual SQL updates (`ALTER TABLE ...` etc), which obviously isn't terribly smooth or scalable. I'm quite happy to keep whatever solution I land on out of this project, though — I'm not convinced that interfacing TypeScript with the database and managing the database schema need to be tightly linked problems.

**Comment by wederer** [comment]
Ok, thanks for your answer!

**Comment by jawj** [comment]
Just came across https://github.com/amacneil/dbmate via HN, which looks quite nice on a cursory inspection ...

**Comment by wederer** [comment]
Thanks for the link. Looks interesting and will save for further projects 👍
